### PR TITLE
Make DataTemplateSelector public

### PR DESCRIPTION
**Pull request by symbiogenesis**
This allows me to override the theming. Such as setting custom colors for records with certain statuses.

### CODE REVIEW

**Comment by akgulebubekir** [comment]
I don't think this is necessary, you can use RowsBackgroundColorPalette and RowsTextColorPalette properties, and implement your own color provider.

i.e:

<dg:DataGrid ItemsSource="{Binding Teams}"  RowsBackgroundColorPalette="{StaticResource YourColorProvider}" ...>


public class YourColorProvider:IColorProvider
{
    public Color GetColor(int rowIndex, object item)
    {
          //your logic
    }

}

**Comment by symbiogenesis** [comment]
Thank you. Just tested it, and it works.

**Comment by daltzctr** [comment]
Kinda sucks you can't do this in a pure XAML way.

**Comment by akgulebubekir** [comment]
@daltzctr actually you can. Here is an example:

```
    <dg:DataGrid.RowsBackgroundColorPalette>
        <dg:PaletteCollection>
            <Color>#F2F2F2</Color>
            <Color>#FFFFFF</Color>
        </dg:PaletteCollection>
    </dg:DataGrid.RowsBackgroundColorPalette>
```

**Comment by daltzctr** [comment]
Yes, but you can't specify app theme in that array

**Comment by symbiogenesis** [comment]
> Yes, but you can't specify app theme in that array

This should work

```xaml
    <ContentPage.Resources>
       <dg:PaletteCollection x:Key="darkPalette">
           <Color>#F2F2F2</Color>
          <Color>#000000</Color>
       </dg:PaletteCollection>
       <dg:PaletteCollection x:Key="lightPalette">
          <Color>#F2F2F2</Color>
          <Color>#FFFFFF</Color>
       </dg:PaletteCollection>
    </ContentPage.Resources>
    <dg:DataGrid RowsBackgroundColorPalette="{AppThemeBinding Dark={StaticResource darkPalette}, Light={StaticResource lightPalette}}">
                <!-- Your DataGrid settings here -->
    </dg:DataGrid>
```

**Comment by daltzctr** [comment]
That's what I ended up doing, but it's a bit cumbersome syntax at best. Thanks though.

**Pull request closed without merging**
