### PR TITLE
add IsVisible property to columns

### PR DESCRIPTION
**Pull request by symbiogenesis**
retry of https://github.com/akgulebubekir/Maui.DataGrid/pull/6 with dynamic width adjustment

### CODE REVIEW

**Review by akgulebubekir — APPROVED** [review]

**Comment by symbiogenesis** [comment]
Merge conflicts resolved

**Comment by symbiogenesis** [comment]
Merging this will fix the current issue with the converter on the main branch.

**Comment by symbiogenesis** [comment]
Resolved

**Comment by symbiogenesis** [comment]
Hi, 

I added tester functionality to the Samples project for the column visibility. It is working now.

**Pull request merged**
